# Define experiment name to be used fro saving the results and logs
exp_name: 'mine_spiral'

# Define parameters for MINE's statistics network
mine:
  var1_size: 1
  var2_size: 1
  hidden: 100
  oc: 1

# Define parameters for generator 
generator:
  z_dim: 10
  hidden: 500
  oc: 2

# Define parameters for discriminator
discriminator:
  oc: 1
  nc: 2
  hidden: 400

# Define parameters for gan
gan:
  d_step: 1

# Define training parameters
lr: 0.0001
use_cuda: True
batch_size: 100
epochs: 10

# Dataset parameters
dataset: 'spiral'  # spiral | 25Gaussians
num_training_points: 100000
num_val_points: 1000
num_workers: 2

# Decide whether to train and/or visualize
training: True
visualize: False

# Define directory locations to save things
logs: './logs/'
results: './results/'