# Define experiment name to be used fro saving the results and logs
exp_name: 'gan_with_mine_spiral_1000_epochs'

# Define parameters for MINE's statistics network
use_mine: True
mine:
  var1_size: 3
  var2_size: 2
  hidden: 100
  oc: 1
  lr: 0.0001
  weight: 0.01
  ma_rate: 0.001

# Define parameters for generator 
generator:
  z_dim: 10
  hidden: 500
  oc: 2
  lr: 0.0001  # If the generator and discriminator are using different learning rates, otherwise use global lr

# Define parameters for discriminator
discriminator:
  oc: 1
  nc: 2
  hidden: 400
  lr: 0.0001  # If the generator and discriminator are using different learning rates, otherwise use the global lr

# Define parameters for gan
gan:
  d_step: 1

# Define training parameters
lr: 0.0001
use_cuda: True
batch_size: 100
epochs: 1000
loggin_interval: 2  # Frequency of running the visualize method.

# Dataset parameters
dataset: 'spiral'  # spiral | 25Gaussians
num_training_points: 100000
num_val_points: 1000
num_workers: 2

# Decide whether to train and/or visualize
training: True
visualize: False

# Define directory locations to save things
logs: './logs/'
results: './results/'
